server:
  port: 8511

spring:
  # Redis的相关配置
  data:
    redis:
      host: 192.168.239.129
      port: 6379
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.239.129:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.239.129:3306/db_system?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
