server:
  port: 8515

spring:
  config:
    import: application-alipay.yml
  application:
    name: service-pay
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.239.129:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.239.129:3306/db_system?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.239.129
      port: 6379

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml